application: vizzualityweb
version: 1
runtime: python
api_version: 1

handlers:

# PyAMF Flash Remoting Gateway
- url: /gateway
  script: gateway.py    
  
# Static: Flash files.
- url: /swfs
  static_dir: swfs
    
# Static: JS files.
- url: /js
  static_dir: js    
  
# Static: CSS files
- url: /css
  static_dir: css
    
# Static: image files
- url: /images
  static_dir: images    
  
# Static: image files
- url: /projects
  static_dir: projects  
  
# Static: image files
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

    
# Examples, each in the examples folder/name_of_example.
# Note: All examples share the same templates, flash, and js folders. 
#- url: /examples/(.*?)(/.*)?
#  script: examples/\1/main.py

# Everything else goes to the main app.
- url: /.*
  script: main.py
  
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (swfs/.*?\.(css|html|fla|js|ttf))|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (psd/.*)|
 (pyamf/tests/.*)|
 (tools/.*)|
 )$

